apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: functions
  namespace: openfaas-fn
  annotations:
    fluxcd.io/automated: "true"
    # Add hyphen to include pre-releases
    filter.fluxcd.io/horizon-householder-appeal-publish: semver:^1.0.0-0
spec:
  releaseName: functions
  chart:
    git: git@github.com:foundry4/appeal-planning-decision.git
    ref: master
    path: charts/functions
  values:
    keyVault:
      name: pins-uks-vault-3203-simo

    horizon-householder-appeal-publish:
      image: pinscommonukscontainers3887default.azurecr.io/horizon-householder-appeal-publish:latest
      appealsServiceUrl: http://app.app-dev.svc.cluster.local:3000
      horizonUrl: http://10.0.7.4:8080
